# Generated by Django 5.2.12 on 2026-04-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0007_club_contact_email_club_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('qr_enabled', models.BooleanField(default=False)),
                ('ics_enabled', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
            ],
            options={
                'ordering': ('start_datetime',),
            },
        ),
        migrations.CreateModel(
            name='ClubEventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.clubevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at',),
                'unique_together': {('event', 'user')},
            },
        ),
    ]
