# Generated by Django 5.2.12 on 2026-04-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
