# Generated by Django 5.2.12 on 2026-04-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_clubevent_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
