# Generated by Django 5.2.12 on 2026-04-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_clubevent_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='location_url',
            field=models.URLField(blank=True),
        ),
    ]
