# Generated by Django 5.2.12 on 2026-04-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_clubevent_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='location_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
