# Generated by Django 5.2.12 on 2026-04-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_clubevent_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubeventattendance',
            name='companions_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
