# Generated by Django 5.2.13 on 2026-04-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_clubeventattendance_companions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevent',
            name='ics_enabled',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='qr_enabled',
        ),
    ]
