# Generated by Django 5.2.13 on 2026-04-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_clubevent_ics_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('query_type', models.CharField(choices=[('clubs_associations', 'Clubes / Asociaciones'), ('fitness_center', 'UAX Fitness Center'), ('internal_leagues_tournaments', 'Ligas internas / Torneos'), ('competition_teams', 'Equipos de competición'), ('individual_sports', 'Deportes individuales'), ('technical_service', 'Servicio Técnico Web')], max_length=40)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField(max_length=1500)),
                ('accepted_privacy', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'solicitud de contacto',
                'verbose_name_plural': 'solicitudes de contacto',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
