# Generated by Django 5.2.13 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_contactrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactrequest",
            old_name="subject",
            new_name="query_topic",
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="query_topic",
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="query_type",
            field=models.CharField(
                choices=[
                    ("clubs_associations", "Clubes / Asociaciones"),
                    ("fitness_center", "UAX Fitness Center"),
                    ("internal_leagues", "Ligas internas"),
                    ("technical_service", "Servicio Técnico Web"),
                ],
                max_length=40,
            ),
        ),
    ]
