# Generated by Django 5.2.13 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_rename_subject_to_query_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="query_type",
            field=models.CharField(
                choices=[
                    ("clubs_associations", "Clubes / Asociaciones"),
                    ("fitness_center", "UAX Fitness Center"),
                    ("internal_leagues", "Ligas internas"),
                    ("competition_teams", "Equipos de competición"),
                    ("individual_sports", "Deportes individuales"),
                    ("technical_service", "Servicio Técnico Web"),
                ],
                max_length=40,
            ),
        ),
    ]
