from django.urls import path

from .views import (
    ClubDetailView,
    ClubListView,
    comment_post_view,
    create_event_view,
    create_poll_view,
    create_post_view,
    close_poll_view,
    delete_comment_view,
    delete_event_attendance_view,
    delete_event_view,
    delete_poll_view,
    delete_resource_view,
    delete_post_view,
    join_club_view,
    join_event_view,
    leave_club_view,
    like_post_view,
    remove_member_view,
    vote_poll_view,
    update_contact_view,
    update_event_attendance_view,
    update_event_view,
    update_general_view,
    update_member_role_view,
    upload_resource_view,
    update_post_view,
)

app_name = "clubs"

# Rutas públicas, operativas y de gestión para el módulo de clubes.
urlpatterns = [
    path("", ClubListView.as_view(), name="list"),
    path("<slug:slug>/join/", join_club_view, name="join"),
    path("<slug:slug>/leave/", leave_club_view, name="leave"),
    path("<slug:slug>/general/", update_general_view, name="update_general"),
    path("<slug:slug>/contact/", update_contact_view, name="update_contact"),
    path("<slug:slug>/memberships/<int:membership_id>/role/", update_member_role_view, name="update_member_role"),
    path("<slug:slug>/memberships/<int:membership_id>/remove/", remove_member_view, name="remove_member"),
    path("<slug:slug>/posts/create/", create_post_view, name="create_post"),
    path("<slug:slug>/posts/<int:post_id>/update/", update_post_view, name="update_post"),
    path("<slug:slug>/posts/<int:post_id>/delete/", delete_post_view, name="delete_post"),
    path("<slug:slug>/posts/<int:post_id>/comment/", comment_post_view, name="comment_post"),
    path(
        "<slug:slug>/posts/<int:post_id>/comments/<int:comment_id>/delete/",
        delete_comment_view,
        name="delete_comment",
    ),
    path("<slug:slug>/posts/<int:post_id>/like/", like_post_view, name="like_post"),
    path("<slug:slug>/polls/create/", create_poll_view, name="create_poll"),
    path("<slug:slug>/polls/<int:poll_id>/vote/", vote_poll_view, name="vote_poll"),
    path("<slug:slug>/polls/<int:poll_id>/close/", close_poll_view, name="close_poll"),
    path("<slug:slug>/polls/<int:poll_id>/delete/", delete_poll_view, name="delete_poll"),
    path("<slug:slug>/events/create/", create_event_view, name="create_event"),
    path("<slug:slug>/events/<int:event_id>/update/", update_event_view, name="update_event"),
    path("<slug:slug>/events/<int:event_id>/join/", join_event_view, name="join_event"),
    path("<slug:slug>/events/<int:event_id>/delete/", delete_event_view, name="delete_event"),
    path(
        "<slug:slug>/events/<int:event_id>/attendances/<int:attendance_id>/delete/",
        delete_event_attendance_view,
        name="delete_event_attendance",
    ),
    path(
        "<slug:slug>/events/<int:event_id>/attendances/<int:attendance_id>/update/",
        update_event_attendance_view,
        name="update_event_attendance",
    ),
    path("<slug:slug>/resources/upload/", upload_resource_view, name="upload_resource"),
    path("<slug:slug>/resources/<int:resource_id>/delete/", delete_resource_view, name="delete_resource"),
    path("<slug:slug>/", ClubDetailView.as_view(), name="detail"),
]
