# Generated by Django 5.2.13 on 2026-04-29 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0020_remove_club_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(default='2025/2026', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Liga interna',
                'verbose_name_plural': 'Ligas internas',
                'ordering': ('sport__display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('captain_name', models.CharField(blank=True, max_length=120)),
                ('players', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sports.league')),
            ],
            options={
                'verbose_name': 'Equipo de liga',
                'verbose_name_plural': 'Equipos de liga',
                'ordering': ('name',),
                'unique_together': {('league', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_day', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sports.leagueteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sports.leagueteam')),
            ],
            options={
                'verbose_name': 'Partido de liga',
                'verbose_name_plural': 'Partidos de liga',
                'ordering': ('played_at', 'match_day', 'id'),
            },
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='sports.sport'),
        ),
        migrations.CreateModel(
            name='SportTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('branch', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('mixed', 'Mixto'), ('individual', 'Individual')], max_length=20)),
                ('coach_name', models.CharField(blank=True, max_length=120)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='clubs.club')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club_teams', to='sports.sport')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('sport', 'name', 'season')},
        ),
        migrations.CreateModel(
            name='SportManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_sports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de deporte',
                'verbose_name_plural': 'Responsables de deporte',
                'ordering': ('sport__name', 'user__username'),
                'unique_together': {('sport', 'user')},
            },
        ),
    ]
