# Generated by Django 5.2.13 on 2026-04-29 23:35

from django.db import migrations


def create_default_sports(apps, schema_editor):
    Sport = apps.get_model("sports", "Sport")
    sports = [
        ("Fútbol sala", "futbol-sala", "Liga interna de fútbol sala."),
        ("Baloncesto", "baloncesto", "Liga interna de baloncesto."),
        ("Pádel", "padel", "Liga interna de pádel."),
    ]

    for order, sport_data in enumerate(sports, start=1):
        name, slug, description = sport_data
        Sport.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "description": description,
                "display_order": order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_sports, migrations.RunPython.noop),
    ]
