# Generated by Django 5.2.13 on 2026-04-29 23:38

from django.db import migrations


def update_default_sport_names(apps, schema_editor):
    Sport = apps.get_model("sports", "Sport")
    updates = {
        "futbol-sala": ("Fútbol sala", "Liga interna de fútbol sala."),
        "padel": ("Pádel", "Liga interna de pádel."),
    }

    for slug, data in updates.items():
        name, description = data
        Sport.objects.filter(slug=slug).update(name=name, description=description)


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_create_default_sports'),
    ]

    operations = [
        migrations.RunPython(update_default_sport_names, migrations.RunPython.noop),
    ]
