# Generated by Django 5.2.13 on 2026-04-29 23:45

from django.db import migrations
from django.db.models import Q


def fix_default_sport_images(apps, schema_editor):
    Sport = apps.get_model("sports", "Sport")
    image_path = "clubs/categories/categoria-deportes-uax.png"
    Sport.objects.filter(
        Q(image__isnull=True) | Q(image=""),
        slug__in=["futbol-sala", "baloncesto", "padel"],
    ).update(image=image_path)


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_add_default_sport_images'),
    ]

    operations = [
        migrations.RunPython(fix_default_sport_images, migrations.RunPython.noop),
    ]
