# Generated by Django 5.2.13 on 2026-06-23 00:40

from django.db import migrations, models


def create_default_facilities(apps, schema_editor):
    SportFacility = apps.get_model("sports", "SportFacility")
    facilities = [
        {
            "name": "Pabellon Deportivo UAX",
            "slug": "pabellon-deportivo-uax",
            "campus": "Campus Villanueva de la Canada",
            "summary": "Espacio cubierto para entrenamientos, partidos de ligas internas y actividades dirigidas.",
            "sports": "Baloncesto\nFutbol sala\nVoleibol",
            "schedule": "Lunes a viernes, 09:00-21:00",
            "access": "Reserva previa para franjas de equipo",
            "image": "sports/facilities/polideportivo_UAX.jpg",
            "display_order": 1,
        },
        {
            "name": "Pistas exteriores",
            "slug": "pistas-exteriores",
            "campus": "Zona deportiva exterior",
            "summary": "Pistas polivalentes para sesiones al aire libre, torneos rapidos y quedadas deportivas.",
            "sports": "Tenis\nPadel\nMultideporte",
            "schedule": "Lunes a domingo, 10:00-20:00",
            "access": "Uso libre segun disponibilidad",
            "image": "sports/facilities/pistas_tenis_uax.jpg",
            "display_order": 2,
        },
        {
            "name": "Campo de futbol",
            "slug": "campo-de-futbol",
            "campus": "Area de competicion",
            "summary": "Campo para entrenamientos de equipos, encuentros amistosos y competiciones universitarias.",
            "sports": "Futbol 7\nFutbol 11\nPreparacion fisica",
            "schedule": "Lunes a viernes, 16:00-22:00",
            "access": "Gestionado por coordinacion deportiva",
            "image": "sports/facilities/campo_futbol_UAX_cCZIYmL.jpg",
            "display_order": 3,
        },
        {
            "name": "UAX Fitness Center",
            "slug": "uax-fitness-center",
            "campus": "Edificio deportivo",
            "summary": "Sala de entrenamiento para fuerza, movilidad y rutinas complementarias de los clubes.",
            "sports": "Fitness\nFuncional\nReadaptacion",
            "schedule": "Lunes a viernes, 08:00-22:00",
            "access": "Acceso con credencial universitaria",
            "image": "sports/facilities/uax_fitness_center.jpg",
            "display_order": 4,
        },
    ]

    for facility in facilities:
        SportFacility.objects.get_or_create(slug=facility["slug"], defaults=facility)


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_fix_default_sport_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/facilities/')),
                ('campus', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('sports', models.TextField(help_text='Introduce un uso o deporte por linea.')),
                ('schedule', models.CharField(max_length=150)),
                ('access', models.CharField(max_length=180)),
                ('map_url', models.URLField(blank=True, verbose_name='Enlace de ubicacion')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Instalacion deportiva',
                'verbose_name_plural': 'Instalaciones deportivas',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.RunPython(create_default_facilities, migrations.RunPython.noop),
    ]
