# Generated by Django 5.2.12 on 2026-04-06 18:53

from django.db import migrations, models


def create_home_settings(apps, schema_editor):
    HomePageSettings = apps.get_model("core", "HomePageSettings")
    HomePageSettings.objects.get_or_create(
        id=1,
        defaults={
            "hero_title": "DEPORTE UNIVERSITARIO UAX",
            "hero_description": (
                "Desarrollo deportivo universitario.\n"
                "Instalaciones de alto rendimiento.\n"
                "Participa en ligas internas y clubes."
            ),
            "hero_button_text_logged_out": "Iniciar sesión",
            "hero_button_text_logged_in": "Explorar clubes",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='DEPORTE UNIVERSITARIO UAX', max_length=200)),
                ('hero_description', models.TextField(default='Desarrollo deportivo universitario.\nInstalaciones de alto rendimiento.\nParticipa en ligas internas y clubes.')),
                ('hero_button_text_logged_out', models.CharField(default='Iniciar sesión', max_length=80)),
                ('hero_button_text_logged_in', models.CharField(default='Explorar clubes', max_length=80)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='core/home/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de la home',
                'verbose_name_plural': 'Configuracion de la home',
            },
        ),
        migrations.RunPython(create_home_settings, migrations.RunPython.noop),
    ]
