# Generated by Django 5.2.12 on 2026-03-27 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category_type', models.CharField(choices=[('life', 'UAX Life'), ('sports', 'Deportivo')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de club',
                'verbose_name_plural': 'Categorías de club',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('club_type', models.CharField(choices=[('life', 'UAX Life'), ('sports', 'Deportivo')], max_length=20)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='clubs/covers/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('current_status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='clubs.clubcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_club', models.CharField(choices=[('member', 'Miembro'), ('captain', 'Capitán'), ('manager', 'Responsable')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('waitlisted', 'Lista de espera'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-joined_at',),
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_waitlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'unique_together': {('club', 'user')},
            },
        ),
    ]
