# Generated by Django 5.2.12 on 2026-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_simplify_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/images/'),
        ),
        migrations.AddField(
            model_name='clubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/categories/'),
        ),
    ]
