# Generated by Django 5.2.12 on 2026-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_image_clubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
