# Generated by Django 5.2.12 on 2026-03-28 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_members_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_clubs', through='clubs.ClubMembership', through_fields=('club', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
