# Generated by Django 5.2.12 on 2026-03-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members_count',
        ),
    ]
