# Generated by Django 5.2.12 on 2026-04-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_contact_email_club_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpost',
            name='post_type',
        ),
    ]
