# Generated by Django 5.2.12 on 2026-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_remove_clubpost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubresource',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
