# Generated by Django 5.2.12 on 2026-04-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubresource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubresource',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
