# Generated by Django 5.2.12 on 2026-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_clubresource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='role_in_club',
            field=models.CharField(choices=[('member', 'Miembro'), ('captain', 'Capitán'), ('manager', 'Responsable'), ('admin', 'Administrador')], default='member', max_length=20),
        ),
    ]
