# Generated by Django 5.2.12 on 2026-04-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_clubmembership_role_in_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_type',
        ),
    ]
