# Generated by Django 5.2.12 on 2026-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_remove_club_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='removal_reason',
            field=models.CharField(blank=True, choices=[('voluntary_leave', 'Baja Voluntaria'), ('finished_studies', 'Finalizó estudios universitarios'), ('low_attendance', 'Poca asistencia'), ('bad_behavior', 'Mal comportamiento'), ('other', 'Otros')], max_length=40),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='removal_reason_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
