# Generated by Django 5.2.12 on 2026-04-08 01:13

from django.db import migrations, models


def truncate_poll_options(apps, schema_editor):
    ClubPollOption = apps.get_model("clubs", "ClubPollOption")
    for option in ClubPollOption.objects.filter(text__isnull=False):
        if len(option.text) > 100:
            option.text = option.text[:100]
            option.save(update_fields=["text"])


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_clubpoll_clubpolloption_clubpollvote'),
    ]

    operations = [
        migrations.RunPython(truncate_poll_options, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clubpolloption',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
