# Generated by Django 5.2.12 on 2026-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_clubpolloption_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpoll',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
