# Generated by Django 5.2.12 on 2026-04-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_clubpoll_opens_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubpoll',
            name='opens_at',
        ),
    ]
