# Generated by Django 5.2.12 on 2026-04-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_remove_clubpoll_opens_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubresource',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
