# Generated by Django 5.2.13 on 2026-04-12 23:50

from django.db import migrations, models


def migrate_waitlisted_memberships(apps, schema_editor):
    ClubMembership = apps.get_model("clubs", "ClubMembership")
    ClubMembership.objects.filter(status="waitlisted").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_clubresource_description'),
    ]

    operations = [
        migrations.RunPython(migrate_waitlisted_memberships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clubmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
