# Generated by Django 5.2.13 on 2026-04-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_clubmembership_status_delete_waitlistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_featured',
        ),
    ]
